INSERT INTO "brands" ("name", "logo_url")
VALUES
  ('AA', 'https://logo.clearbit.com/aa.co.nz'),
  ('Adairs', 'https://logo.clearbit.com/adairs.co.nz'),
  ('Air New Zealand', 'https://logo.clearbit.com/airnewzealand.co.nz'),
  ('ASOS', 'https://logo.clearbit.com/asos.com'),
  ('Ballantynes', 'https://logo.clearbit.com/ballantynes.co.nz'),
  ('Booking.com', 'https://logo.clearbit.com/booking.com'),
  ('BP', 'https://logo.clearbit.com/bp.com'),
  ('Briscoes', 'https://logo.clearbit.com/briscoes.co.nz'),
  ('Bunnings Warehouse', 'https://logo.clearbit.com/bunnings.co.nz'),
  ('Burnsco', 'https://logo.clearbit.com/burnsco.co.nz'),
  ('City Chic', 'https://logo.clearbit.com/citychic.com.au'),
  ('Coffee Culture', 'https://logo.clearbit.com/coffeeculture.co.nz'),
  ('Cotton On', 'https://logo.clearbit.com/cottonon.com'),
  ('Culture Kings', 'https://logo.clearbit.com/culturekings.com.au'),
  ('EB Games', 'https://logo.clearbit.com/ebgames.co.nz'),
  ('Everyday Rewards', 'https://logo.clearbit.com/everydayrewards.co.nz'),
  ('Farmers', 'https://logo.clearbit.com/farmers.co.nz'),
  ('Flybuys', 'https://logo.clearbit.com/flybuys.co.nz'),
  ('Foot Locker', 'https://logo.clearbit.com/footlocker.co.nz'),
  ('Hachi Hachi', 'https://logo.clearbit.com/hachihachi.co.nz'),
  ('Health 2000', 'https://logo.clearbit.com/health2000.co.nz'),
  ('Hoyts', 'https://logo.clearbit.com/hoyts.co.nz'),
  ('JB Hi-Fi', 'https://logo.clearbit.com/jbhifi.co.nz'),
  ('Jaycar', 'https://logo.clearbit.com/jaycar.co.nz'),
  ('Just Jeans', 'https://logo.clearbit.com/justjeans.co.nz'),
  ('Kathmandu', 'https://logo.clearbit.com/kathmandu.co.nz'),
  ('Kmart', 'https://logo.clearbit.com/kmart.co.nz'),
  ('Lego', 'https://logo.clearbit.com/lego.com'),
  ('Living Rewards', 'https://logo.clearbit.com/livingrewards.co.nz'),
  ('Mecca', 'https://logo.clearbit.com/mecca.com'),
  ('Millers', 'https://logo.clearbit.com/millers.co.nz'),
  ('Mitre 10', 'https://logo.clearbit.com/mitre10.co.nz'),
  ('Mobile City', 'https://logo.clearbit.com/mobilecity.co.nz'),
  ('Mountain Warehouse', 'https://logo.clearbit.com/mountainwarehouse.com'),
  ('Muffin Break', 'https://logo.clearbit.com/muffinbreak.co.nz'),
  ('New World', 'https://logo.clearbit.com/newworld.co.nz'),
  ('Noel Leeming', 'https://logo.clearbit.com/noelleeming.co.nz'),
  ('PAK''nSAVE', 'https://logo.clearbit.com/paknsave.co.nz'),
  ('Paper Plus', 'https://logo.clearbit.com/paperplus.co.nz'),
  ('PB Tech', 'https://logo.clearbit.com/pbtech.co.nz'),
  ('PlaceMakers', 'https://logo.clearbit.com/placemakers.co.nz'),
  ('Postie', 'https://logo.clearbit.com/postie.co.nz'),
  ('Rebel Sport', 'https://logo.clearbit.com/rebelsport.co.nz'),
  ('Repco', 'https://logo.clearbit.com/repco.co.nz'),
  ('Resene', 'https://logo.clearbit.com/resene.co.nz'),
  ('Sephora', 'https://logo.clearbit.com/sephora.nz'),
  ('SHEIN', 'https://logo.clearbit.com/shein.com'),
  ('Spotlight', 'https://logo.clearbit.com/spotlightstores.com'),
  ('Strandbags', 'https://logo.clearbit.com/strandbags.co.nz'),
  ('Subway', 'https://logo.clearbit.com/subway.com'),
  ('Supercheap Auto', 'https://logo.clearbit.com/supercheapauto.co.nz'),
  ('SuperGold', 'https://logo.clearbit.com/supergold.govt.nz'),
  ('Taking Shape', 'https://logo.clearbit.com/takingshape.com'),
  ('The Athlete''s Foot', 'https://logo.clearbit.com/thealthletesfoot.co.nz'),
  ('The Warehouse', 'https://logo.clearbit.com/thewarehouse.co.nz'),
  ('Uber Eats', 'https://logo.clearbit.com/ubereats.com'),
  ('Whitcoulls', 'https://logo.clearbit.com/whitcoulls.co.nz'),
  ('Woolworths', 'https://logo.clearbit.com/woolworths.co.nz');
